import math
import struct
from pathlib import Path

import tinysoundfont as tsf


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "include" / "musicbox_sample_data.h"
DEFAULT_FULL_SF3 = PROJECT_ROOT / "assets" / "MuseScore_General_Full.sf3"
DEFAULT_LITE_SF3 = PROJECT_ROOT / "assets" / "MuseScore_General_Lite.sf3"

TARGET_SAMPLE_RATE = 12000
TARGET_GAIN = 108.0
NOTE_HOLD_SECONDS = 0.035
NOTE_RENDER_SECONDS = 1.05
GM_MUSIC_BOX_PRESET = 10
ROOT_MIDI_NOTES = tuple(range(36, 97, 3))


def pick_soundfont_path() -> Path:
    if DEFAULT_FULL_SF3.exists():
        return DEFAULT_FULL_SF3
    if DEFAULT_LITE_SF3.exists():
        return DEFAULT_LITE_SF3
    raise FileNotFoundError(
        "No MuseScore soundfont found. Expected assets/MuseScore_General_Full.sf3 "
        "or assets/MuseScore_General_Lite.sf3"
    )


def trim_silence(samples: list[float], threshold: float = 0.00025) -> list[float]:
    start = 0
    while start < len(samples) and abs(samples[start]) < threshold:
        start += 1

    end = len(samples)
    while end > start and abs(samples[end - 1]) < threshold:
        end -= 1

    if start >= end:
        return [0.0]
    return samples[start:end]


def dc_block(samples: list[float]) -> list[float]:
    estimate = 0.0
    filtered = []
    for value in samples:
        estimate += (value - estimate) * 0.0035
        filtered.append(value - estimate)
    return filtered


def soften_tail(samples: list[float], sample_rate: int) -> None:
    attack = max(1, int(sample_rate * 0.0012))
    release = max(1, int(sample_rate * 0.08))

    for index in range(min(attack, len(samples))):
        samples[index] *= index / attack

    for offset in range(min(release, len(samples))):
        index = len(samples) - offset - 1
        samples[index] *= offset / release


def normalize(samples: list[float]) -> list[int]:
    peak = max(abs(value) for value in samples) or 1.0
    scale = TARGET_GAIN / peak
    quantized = []
    for value in samples:
        clamped = max(-127.0, min(127.0, value * scale))
        quantized.append(int(round(clamped)))
    return quantized


def render_note(synth: tsf.Synth, sfid: int, midi_note: int) -> list[int]:
    synth.program_select(0, sfid, 0, GM_MUSIC_BOX_PRESET)
    synth.noteon(0, midi_note, 110)
    attack_samples = int(TARGET_SAMPLE_RATE * NOTE_HOLD_SECONDS)
    tail_samples = int(TARGET_SAMPLE_RATE * (NOTE_RENDER_SECONDS - NOTE_HOLD_SECONDS))

    left = []
    def pull_left_channel(sample_count: int) -> None:
        frame_bytes = bytes(synth.generate_simple(sample_count))
        for left_sample, _right_sample in struct.iter_unpack("<ff", frame_bytes):
            left.append(left_sample)

    pull_left_channel(attack_samples)

    synth.noteoff(0, midi_note)
    pull_left_channel(tail_samples)

    synth.sounds_off()
    processed = trim_silence(dc_block(left))
    soften_tail(processed, TARGET_SAMPLE_RATE)
    return normalize(processed)


def main() -> None:
    soundfont_path = pick_soundfont_path()
    synth = tsf.Synth(gain=-3.0, samplerate=TARGET_SAMPLE_RATE)
    sfid = synth.sfload(str(soundfont_path), gain=0.0, max_voices=64)

    arrays = []
    entries = []
    for midi_note in ROOT_MIDI_NOTES:
        print("rendering", midi_note)
        quantized = render_note(synth, sfid, midi_note)
        symbol = f"kMusicBoxSample{midi_note}"
        arrays.append(
            f"constexpr int8_t {symbol}[] = {{{', '.join(str(v) for v in quantized)}}};"
        )
        entries.append(f"    {{{midi_note}, {len(quantized)}, {symbol}}},")

    header = f"""#pragma once

#include <stddef.h>
#include <stdint.h>

// Generated by scripts/generate_musicbox_sample_bank.py
// Source soundfont: {soundfont_path.as_posix()}
// Preset: GM bank 0 preset 10 (Music Box)
namespace MusicBoxSampleData {{

constexpr uint32_t kSampleRate = {TARGET_SAMPLE_RATE};

struct Sample {{
  uint8_t midi;
  uint16_t length;
  const int8_t* data;
}};

{chr(10).join(arrays)}

constexpr Sample kSamples[] = {{
{chr(10).join(entries)}
}};

constexpr size_t kSampleCount = sizeof(kSamples) / sizeof(kSamples[0]);

}}  // namespace MusicBoxSampleData
"""
    OUTPUT_PATH.write_text(header, encoding="ascii")
    print("wrote", OUTPUT_PATH)


if __name__ == "__main__":
    main()
