import io
import math
import struct
import urllib.request
import wave
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "include" / "piano_sample_data.h"

SOURCE_FILES = [
    ("c1.wav", 24),
    ("c1s.wav", 25),
    ("d1.wav", 26),
    ("d1s.wav", 27),
    ("e1.wav", 28),
    ("f1.wav", 29),
    ("f1s.wav", 30),
    ("g1.wav", 31),
    ("g1s.wav", 32),
    ("a1.wav", 33),
    ("a1s.wav", 34),
    ("b1.wav", 35),
    ("c2.wav", 36),
]

TARGET_SAMPLE_RATE = 12000
TARGET_DURATION_SECONDS = 0.42
TARGET_GAIN = 118.0
PITCH_SHIFT_SEMITONES = 24


def read_wav_from_url(url: str):
    with urllib.request.urlopen(url, timeout=30) as response:
        payload = response.read()

    with wave.open(io.BytesIO(payload), "rb") as wav_file:
        channels = wav_file.getnchannels()
        sample_width = wav_file.getsampwidth()
        sample_rate = wav_file.getframerate()
        frame_count = wav_file.getnframes()
        frames = wav_file.readframes(frame_count)

    if sample_width != 2:
        raise RuntimeError(f"unsupported sample width {sample_width} for {url}")

    samples = struct.unpack("<" + "h" * (len(frames) // 2), frames)
    if channels == 1:
        mono = [value / 32768.0 for value in samples]
    else:
        mono = []
        for index in range(0, len(samples), channels):
            frame = samples[index:index + channels]
            mono.append(sum(frame) / (32768.0 * channels))
    return mono, sample_rate


def trim_silence(samples):
    threshold = 0.015
    start = 0
    while start < len(samples) and abs(samples[start]) < threshold:
      start += 1

    end = len(samples)
    while end > start and abs(samples[end - 1]) < threshold:
      end -= 1

    if start >= end:
        return [0.0]

    return samples[start:end]


def resample(samples, source_rate, target_rate, rate_scale=1.0, duration_seconds=None):
    if duration_seconds is None:
        duration_seconds = len(samples) / source_rate / rate_scale
    target_count = max(1, int(round(duration_seconds * target_rate)))
    output = []
    for index in range(target_count):
        source_pos = index * source_rate * rate_scale / target_rate
        if source_pos >= len(samples) - 1:
            sample = samples[-1]
        else:
            left_index = int(source_pos)
            fraction = source_pos - left_index
            left_value = samples[left_index]
            right_value = samples[left_index + 1]
            sample = left_value + (right_value - left_value) * fraction
        output.append(sample)
    return output


def apply_fade(samples, sample_rate):
    attack = max(1, int(sample_rate * 0.003))
    release = max(1, int(sample_rate * 0.035))
    total = len(samples)

    for index in range(min(attack, total)):
        samples[index] *= index / attack

    for offset in range(min(release, total)):
        index = total - offset - 1
        samples[index] *= offset / release


def normalize(samples):
    peak = max(abs(value) for value in samples) or 1.0
    scale = TARGET_GAIN / peak
    quantized = []
    for value in samples:
        clamped = max(-127.0, min(127.0, value * scale))
        quantized.append(int(round(clamped)))
    return quantized


def main():
    arrays = []
    entries = []
    for filename, midi in SOURCE_FILES:
        url = f"https://raw.githubusercontent.com/parisjava/wav-piano-sound/master/wav/{filename}"
        print("fetching", url)
        samples, source_rate = read_wav_from_url(url)
        samples = trim_silence(samples)
        shifted_rate_scale = 2 ** (PITCH_SHIFT_SEMITONES / 12.0)
        shifted = resample(
            samples,
            source_rate,
            TARGET_SAMPLE_RATE,
            rate_scale=shifted_rate_scale,
            duration_seconds=TARGET_DURATION_SECONDS,
        )
        apply_fade(shifted, TARGET_SAMPLE_RATE)
        quantized = normalize(shifted)

        base_midi = midi + PITCH_SHIFT_SEMITONES
        symbol = f"kPianoSample{base_midi}"
        array_values = ", ".join(str(value) for value in quantized)
        arrays.append(f"constexpr int8_t {symbol}[] = {{{array_values}}};")
        entries.append(
            "    {" + f"{base_midi}, {len(quantized)}, {symbol}" + "},"
        )

    header = f"""#pragma once

#include <stddef.h>
#include <stdint.h>

// Generated by scripts/generate_piano_sample_bank.py
// Source samples: https://github.com/parisjava/wav-piano-sound (Unlicense/public domain)
namespace PianoSampleData {{

constexpr uint32_t kSampleRate = {TARGET_SAMPLE_RATE};

struct Sample {{
  uint8_t midi;
  uint16_t length;
  const int8_t* data;
}};

{chr(10).join(arrays)}

constexpr Sample kSamples[] = {{
{chr(10).join(entries)}
}};

constexpr size_t kSampleCount = sizeof(kSamples) / sizeof(kSamples[0]);

}}  // namespace PianoSampleData
"""
    OUTPUT_PATH.write_text(header, encoding="ascii")
    print("wrote", OUTPUT_PATH)


if __name__ == "__main__":
    main()
