from pathlib import Path
import argparse

import mido


def collect_events(track):
    absolute_tick = 0
    active = {}
    events = []
    for message in track:
        absolute_tick += message.time
        if message.type == "note_on" and message.velocity > 0:
            active[(message.note, message.channel)] = (absolute_tick, message.velocity)
        elif message.type in ("note_off", "note_on") and (
            message.type == "note_off" or message.velocity == 0
        ):
            start = active.pop((message.note, message.channel), None)
            if start is not None:
                events.append((start[0], absolute_tick - start[0], message.note, start[1]))
    return events


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--midi", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--namespace", required=True)
    parser.add_argument("--source-url", required=True)
    args = parser.parse_args()

    midi_path = Path(args.midi)
    output_path = Path(args.output)
    midi = mido.MidiFile(str(midi_path))
    tempo = 500000
    all_events = []

    for track_index, track in enumerate(midi.tracks):
        absolute_tick = 0
        for message in track:
            absolute_tick += message.time
            if message.type == "set_tempo":
                tempo = message.tempo
                break

        events = collect_events(track)
        if not events:
            continue

        average_note = sum(event[2] for event in events) / len(events)
        role = 0 if average_note >= 60 else 1
        for start_tick, duration_ticks, midi_note, velocity in events:
            all_events.append((start_tick, duration_ticks, midi_note, velocity, role))

    all_events.sort(key=lambda item: (item[0], item[4], -item[2]))

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(
        f"// Generated by scripts/generate_song_midi_header.py from {midi_path.as_posix()}"
    )
    lines.append(f"// Source MIDI: {args.source_url}")
    lines.append(f"namespace {args.namespace} {{")
    lines.append("")
    lines.append(f"constexpr uint16_t kTicksPerBeat = {midi.ticks_per_beat};")
    lines.append(f"constexpr uint32_t kTempoMicrosecondsPerBeat = {tempo};")
    lines.append("")
    lines.append("struct Event {")
    lines.append("  uint32_t start_tick;")
    lines.append("  uint32_t duration_tick;")
    lines.append("  uint8_t midi;")
    lines.append("  uint8_t velocity;")
    lines.append("  uint8_t role;")
    lines.append("};")
    lines.append("")
    lines.append("constexpr Event kEvents[] = {")
    for event in all_events:
      lines.append(
          f"    {{{event[0]}, {event[1]}, {event[2]}, {event[3]}, {event[4]}}},"
      )
    lines.append("};")
    lines.append("")
    lines.append("constexpr size_t kEventCount = sizeof(kEvents) / sizeof(kEvents[0]);")
    lines.append("")
    lines.append(f"}}  // namespace {args.namespace}")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="ascii")
    print("wrote", output_path, "events", len(all_events))


if __name__ == "__main__":
    main()
