from pathlib import Path

import mido


PROJECT_ROOT = Path(__file__).resolve().parents[1]
MIDI_PATH = PROJECT_ROOT / "assets" / "canon_in_d.mid"
OUTPUT_PATH = PROJECT_ROOT / "include" / "canon_midi_data.h"


def collect_events(track):
    absolute_tick = 0
    active = {}
    events = []
    for message in track:
        absolute_tick += message.time
        if message.type == "note_on" and message.velocity > 0:
            active[(message.note, message.channel)] = (absolute_tick, message.velocity)
        elif message.type in ("note_off", "note_on") and (
            message.type == "note_off" or message.velocity == 0
        ):
            start = active.pop((message.note, message.channel), None)
            if start is not None:
                events.append((start[0], absolute_tick - start[0], message.note, start[1]))
    return events


def main():
    midi = mido.MidiFile(MIDI_PATH)
    all_events = []
    tempo = 500000

    for track_index, track in enumerate(midi.tracks):
        absolute_tick = 0
        for message in track:
            absolute_tick += message.time
            if message.type == "set_tempo":
                tempo = message.tempo
                break

        for start_tick, duration_ticks, midi_note, velocity in collect_events(track):
            role = 0 if track_index == 0 else 1
            all_events.append((start_tick, duration_ticks, midi_note, velocity, role))

    all_events.sort(key=lambda item: (item[0], item[4], -item[2]))

    lines = []
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("// Generated by scripts/generate_canon_midi_header.py from assets/canon_in_d.mid")
    lines.append("// Source MIDI: https://midisheetmusic.com/songs/Pachelbel__Canon_in_D_major.mid")
    lines.append("namespace CanonMidiData {")
    lines.append("")
    lines.append(f"constexpr uint16_t kTicksPerBeat = {midi.ticks_per_beat};")
    lines.append(f"constexpr uint32_t kTempoMicrosecondsPerBeat = {tempo};")
    lines.append("")
    lines.append("struct Event {")
    lines.append("  uint16_t start_tick;")
    lines.append("  uint16_t duration_tick;")
    lines.append("  uint8_t midi;")
    lines.append("  uint8_t velocity;")
    lines.append("  uint8_t role;")
    lines.append("};")
    lines.append("")
    lines.append("constexpr Event kEvents[] = {")
    for event in all_events:
        lines.append(
            f"    {{{event[0]}, {event[1]}, {event[2]}, {event[3]}, {event[4]}}},"
        )
    lines.append("};")
    lines.append("")
    lines.append("constexpr size_t kEventCount = sizeof(kEvents) / sizeof(kEvents[0]);")
    lines.append("")
    lines.append("}  // namespace CanonMidiData")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="ascii")
    print("wrote", OUTPUT_PATH)
    print("events", len(all_events))


if __name__ == "__main__":
    main()
